all: stream-talk-client.c stream-talk-server.c
	gcc -Wall -pedantic -L. -g -o file_client stream-talk-client.c -lpacketErrorSend
	gcc -Wall -pedantic -L. -g -o file_server stream-talk-server.c -lpacketErrorSend
